### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by vascowhite** [NickBusey/BulletNotes#5]
This looks like a great project, thanks for all the hard work!
The biggest attraction for me is the option to self host the app. Do you have a guide for installation on a server that won't be used for development?

Keep up the good work.

**Comment by NickBusey** [comment]
Thanks!

The Heroku Deployment Guide is the only thing like that so far https://github.com/NickBusey/BulletNotes#heroku-deployment

I haven't tried to host it anywhere else, so I don't really have a guide for that. Your best bet there is probably the Meteor Deployment Guide https://guide.meteor.com/deployment.html

Your main thing would just be making sure your Mongo DB gets backed up regularly. If you want to use features like file uploads to s3 you'll need s3 api keys to plug into settings.json. I'd be happy to merge any documentation improvements if you give it a shot and run into issues.

**Comment by vascowhite** [comment]
Thanks Nick,

I thought that would be the case, but wanted to check if you had anything else.
I'll give it a go and if I get anywhere I'll ley you know what steps I took.
